# -*- coding: utf-8 -*-
"""05-entrada.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvDb92z70XY3y6bcvU7-oc4AcdXvgq5i

# 99 Bottles of Rum on the Wall

De tantas solicitudes que ha recibido, Pyratilla no cabe en sí de la emoción y se pone a cantar

<ul type = "none">
<li>"99 bottles of rum on the wall, 99 bottles of rum. </li>
<li>Take one down, pass it around, 98 bottles of rum on the wall. </li>
<li>98 bottles of rum on the wall, 98 bottles of rum. </li>
<li>Take one down, pass it around, 97 bottles of rum on the wall..." </li>
</ul>


Ayuda a Pyratilla a cantar la canción al completo con un bucle `while`.
"""

i = 99
while i >= 0:
  print("{} bottles of rum on the wall,{} bottles of rum.".format (i,i))
  print("Take one down, pass it around,{} bottles of rum on the wall.".format(i-1))
  i -= 1

"""Ayuda a Pyratilla a cantar la canción al completo con un bucle `for`."""

for i in range (99, 0, -1):
  print("{} bottles of rum on the wall,{} bottles of rum.".format (i,i))
  print("Take one down, pass it around,{} bottles of rum on the wall.".format(i-1))